### ISSUE TITLE
Question about nuplan_planner_tutorial

### ISSUE THREAD

**Issue by IvanChen777** [motional/nuplan-devkit#136] opened 2022-09-28 07:49 UTC
When I have installed all the packages from requirements.txt and run the nuplan_planner_tutorial. I met a problem. When I try to run launch simulation(Within the notebook) block, it seems like my kernel is always dying, because it has the error called:
Error: Canceled future for execute_request message before replies were done. Is there someone knows how to solve this problem?
Thank you in advance!

**Comment by IvanChen777** [comment] 2022-09-29 09:18
<img width="1352" alt="截屏2022-09-29 11 13 47" src="https://user-images.githubusercontent.com/91310432/192991957-c0309f20-cc50-4e59-93a9-6f3618e262bc.png">
I built the environment as the tutorial described in the website, install all the packages from requirements.txt, and activate the nuplan environment, I run it in vscode, I don't know what else do you need? But thank you in advance!

**Comment by JingyuQian** [comment] 2022-09-30 22:51
Hello, it looks like it's a problem related to the vscode's Jupyter plugin. Should have nothing to do with NuPlan itself. Maybe try one of the following:
1) update vscode, jupyter plugin, or try changing another version of them;
2) directly use Jupyter instead of using it inside vscode;

**Comment by IvanChen777** [comment] 2022-10-03 11:12
Hi,@JingyuQian, thank you for your answer: ) But these 2 methods seems that not useful... my computer is Macbook pro 16, intel i9. Do you think if it is enough to run the Nuplan? Thank you in advance!

**Comment by JingyuQian** [comment] 2022-10-03 18:29
Hello @IvanChen777, Looks like this is a memory problem. See [this issue](https://github.com/microsoft/vscode-jupyter/issues/9741). 

In short, the problem can arise from different causes (therefore no official fixes yet), but most likely due to memory shortage. Try to lower your resources in the config when running the tutorial (such as the number of workers, etc.), and if that doesn't work, better use another computer to save time...

**Comment by IvanChen777** [comment] 2022-10-06 19:35
Hi, ,@JingyuQian, thank you for your reply, after I apply another computer, this error disappears. However, new error comes, after I install the environment by following the instruction, this error appears, then I follow the error instruction, and change the version of protobuf to 3.20.x, and also try the second method, it seems not working... and also I find that there will be a conflict if I change the version of protobuf. Do you have some suggestions? Thank you :)
<img width="904" alt="截屏2022-10-06 21 31 07" src="https://user-images.githubusercontent.com/91310432/194402339-40ed5cd4-55df-43c0-8e93-9afa8bff34b1.png">
<img width="1232" alt="截屏2022-10-06 21 33 57" src="https://user-images.githubusercontent.com/91310432/194402841-e7bec709-b41d-4d16-97e6-20c20ea115cb.png">

**Comment by JingyuQian** [comment] 2022-10-06 19:58
Hi @IvanChen777 , don't know if [this issue](https://github.com/tensorflow/tensorboard/issues/5703#issuecomment-1125184321) will help.
Since this is a different problem from your original title, if you're able to reproduce this error, you can create another new issue and ask the officials to help resolve it.

**Comment by michael-motional** [comment] 2022-10-06 20:03
@IvanChen777 to follow up on the original issue, can you see if you can replicate the issue running outside the notebook?

For the new issue, are you running into that when running `conda env create -f environment.yml`?

**Comment by IvanChen777** [comment] 2022-10-06 20:14
> Hi @IvanChen777 , don't know if [this issue](https://github.com/tensorflow/tensorboard/issues/5703#issuecomment-1125184321) will help. Since this is a different problem from your original title, if you're able to reproduce this error, you can create another new issue and ask the officials to help resolve it.

Okay, thank you for your advice:)

**Comment by IvanChen777** [comment] 2022-10-06 20:17
> @IvanChen777 to follow up on the original issue, can you see if you can replicate the issue running outside the notebook?
> 
> For the new issue, are you running into that when running `conda env create -f environment.yml`?
Hi, for the original issue, what do you mean that outside the notebook, and for the new issue, I run the conda env create -f environment.yml in order to build the environment

**Comment by michael-motional** [comment] 2022-10-06 20:55
I was suggesting you run the contents of the notebook from a regular python file, something like [this file](https://gist.github.com/michael-motional/ed0f65a3d07c8bdc4a55a41dad6da079). You might have to change `BASE_CONFIG_PATH` depending on where you run it from, in the example file I set it to run from the base of `nuplan-devkit`. The hope is any issues might be more likely to surface than when running through the notebook.

**Comment by michael-motional** [comment] 2022-10-08 16:43
I'll close this, but please re-open if you'd like to discuss further

**Closed by michael-motional** 2022-10-08 16:43 UTC

**Comment by luis2r** [comment] 2022-10-09 23:20
> 

Same issue running regular python file

**Comment by luis2r** [comment] 2022-10-09 23:22
> I was suggesting you run the contents of the notebook from a regular python file, something like [this file](https://gist.github.com/michael-motional/ed0f65a3d07c8bdc4a55a41dad6da079). You might have to change `BASE_CONFIG_PATH` depending on where you run it from, in the example file I set it to run from the base of `nuplan-devkit`. The hope is any issues might be more likely to surface than when running through the notebook.

same issue running a regular python file

**Comment by IvanChen777** [comment] 2022-10-10 06:28
Thank you very much! This problem is solved!

________________________________
发件人: Michael Noronha ***@***.***>
发送时间: 2022年10月9日 0:43:54
收件人: motional/nuplan-devkit
抄送: Chen Yifeng; Mention
主题: Re: [motional/nuplan-devkit] Question about nuplan_planner_tutorial (Issue #136)


I'll close this, but please re-open if you'd like to discuss further

―
